# Đề bài về nhà

## Yêu cầu

- Tự viết code cho mô hình Linear Regression theo công thức đã được dạy trong buổi lý thuyết trên lớp.
- Tự viết hàm dự đoán.
- Huấn luyện cả mô hình của thư viện và mô hình mình tự viết.
- In ra các trọng số: w0, w1, w2, ..., wn của cả 2 mô hình đã huấn luyện để quan sát và so sánh.
- Dự đoán dữ liệu tập test bằng cả 2 mô hình (mô hình thư viện thì dùng hàm predict() của thư viện, mô hình tự viết dùng hàm dự đoán tự viết), in ra kết quả bằng Dataframe như trong bài thực hành trên lớp.
- Tính RMSE trên tập test cho cả 2 mô hình và so sánh.

## Dữ liệu 

Tập dữ liệu giá nhà ở Boston đã có sẵn trên sklearn, dữ liệu đã được chuẩn hóa và chia thành tập train, tập test

In [6]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
import math 

from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# Đọc dữ liệu 

Dữ liệu về giá nhà ở Boston được hỗ trợ bởi sklearn, đọc dữ liệu thông qua hàm `datasets.load_boston()` 

Xem thêm các bộ dữ liệu khác tại https://scikit-learn.org/stable/datasets/index.html#toy-datasets. 

Dữ liệu được chia thành các thành phần data và target như tập diabetes. Dữ liệu cũng đã được chuẩn hóa, chỉ cần gọi ra và huấn luyện

In [7]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.concatenate([raw_df.values[::2, :], raw_df.values[1::2, :2]],axis=1)
target = raw_df.values[1::2, 2]
print("Số chiều dữ liệu input: ", data.shape)
print("Số chiều dữ liệu target: ",target.shape)
print("5 mẫu dữ liệu đầu tiên:")
print("input: ", data[:5])
print("target: ",target[:5])


Số chiều dữ liệu input:  (506, 13)
Số chiều dữ liệu target:  (506,)
5 mẫu dữ liệu đầu tiên:
input:  [[6.3200e-03 1.8000e+01 2.3100e+00 0.0000e+00 5.3800e-01 6.5750e+00
  6.5200e+01 4.0900e+00 1.0000e+00 2.9600e+02 1.5300e+01 3.9690e+02
  4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 6.4210e+00
  7.8900e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9690e+02
  9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 7.1850e+00
  6.1100e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9283e+02
  4.0300e+00]
 [3.2370e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01 6.9980e+00
  4.5800e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01 3.9463e+02
  2.9400e+00]
 [6.9050e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01 7.1470e+00
  5.4200e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01 3.9690e+02
  5.3300e+00]]
target:  [24.  21.6 34.7 33.4 36.2]


**Chia dữ liệu làm 2 phần training 362 mẫu và testing 80 mẫu** 

In [44]:
# cat nho du lieu, lay 1 phan cho qua trinh thu nghiem,
# chia train test cac mau du lieu
# dataset_X = dataset.data[:, np.newaxis, 2]
dataset_X = data
dataset_X_train = dataset_X[:404]
dataset_y_train = target[:404]

dataset_X_test = dataset_X[405:]
dataset_y_test = target[405:]
dataset_X_train.shape


(404, 13)

# Xây dựng mô hình

## Xây dựng mô hình bằng thư viện

In [28]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()


## Xây dựng mô hình Linear Regression tự viết 

In [49]:
one=np.ones((dataset_X_train.shape[0],1))
A=np.concatenate((one,dataset_X_train),axis=1)
A.shape

(404, 14)

## Hàm test mô hình tự viết

In [58]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
def test_model(y_pred,y_test):
    print(r2_score(y_test,y_pred))
    print(means_squared_error(y_test,y_pred))
    print(mean_absolute_error(y_test,y_pred))

# Huấn luyện mô hình

## Huấn luyện mô hình của thư viện

In [46]:
reg.fit(dataset_X_train,dataset_y_train)
reg.coef_

array([-2.02135297e-01,  4.41276341e-02,  5.26739364e-02,  1.88474315e+00,
       -1.49281487e+01,  4.76038673e+00,  2.88734527e-03, -1.30025278e+00,
        4.61661953e-01, -1.55434673e-02, -8.11632369e-01, -1.97174433e-03,
       -5.32273431e-01])

## Training mô hình bằng Linear regression tự viết

In [51]:
w=np.dot (np. linalg.inv(np.dot(A.T,A)),np.dot(A.T,dataset_y_train))
w

array([ 3.00771669e+01, -2.02135297e-01,  4.41276341e-02,  5.26739364e-02,
        1.88474315e+00, -1.49281487e+01,  4.76038673e+00,  2.88734527e-03,
       -1.30025278e+00,  4.61661953e-01, -1.55434673e-02, -8.11632369e-01,
       -1.97174433e-03, -5.32273431e-01])

# Dự đoán các mẫu dữ liệu

## Dự đoán các mẫu dữ liệu theo mô hình của thư viện

In [50]:
y_pred1=reg.predict(dataset_X_test)
y_pred1

array([ 3.78705697,  6.64054968, 21.31276497, 15.41271412, 23.65229756,
       16.5856869 , 22.2398228 ,  4.59739429, 12.3169525 , -4.44125395,
       14.58699578, 19.44878328,  8.91710678,  5.65808812, 20.43111408,
       22.17125684, 20.66658612, 20.28490422, 19.04039215, 19.73961052,
       14.88382776, 21.13129199, 17.17770988, 19.28271938, 18.49086819,
       23.17359203, 24.05552964, 26.68692039, 22.64112485, 20.57172202,
       18.52528873, 20.16236932, 14.23753201,  9.44743091, 14.15251822,
       12.85517737, 19.29064244, 20.84754265, 20.09364492, 14.27333565,
       17.74701701, 20.71930787, 19.97203851, 19.18863916, 20.31063775,
       23.45234188, 22.38371917, 20.90114965, 25.69227454, 21.87873152,
       22.15274176, 18.98327823, 18.91436618, 20.5953674 , 20.39616439,
       23.28568554, 22.67323362, 21.90107552, 24.91067603, 22.07465271,
       20.33275353, 20.49535154, 19.29672605, 17.81302376, 19.11160043,
       22.02849443, 24.86005763, 24.6577531 , 28.44253746, 17.61

## Dự đoán các mẫu dữ liệu tính theo linear regression tự viết

In [54]:
A_test=np.concatenate((np.ones((dataset_X_test.shape[0],1)),dataset_X_test),axis=1)
y_pred2=np.dot(A_test,w)
y_pred2

array([ 3.78705697,  6.64054968, 21.31276497, 15.41271412, 23.65229756,
       16.5856869 , 22.2398228 ,  4.59739429, 12.3169525 , -4.44125395,
       14.58699578, 19.44878328,  8.91710678,  5.65808812, 20.43111408,
       22.17125684, 20.66658612, 20.28490422, 19.04039215, 19.73961052,
       14.88382776, 21.13129199, 17.17770988, 19.28271938, 18.49086819,
       23.17359203, 24.05552964, 26.68692039, 22.64112485, 20.57172202,
       18.52528873, 20.16236932, 14.23753201,  9.44743091, 14.15251822,
       12.85517737, 19.29064244, 20.84754265, 20.09364492, 14.27333565,
       17.74701701, 20.71930787, 19.97203851, 19.18863916, 20.31063775,
       23.45234188, 22.38371917, 20.90114965, 25.69227454, 21.87873152,
       22.15274176, 18.98327823, 18.91436618, 20.5953674 , 20.39616439,
       23.28568554, 22.67323362, 21.90107552, 24.91067603, 22.07465271,
       20.33275353, 20.49535154, 19.29672605, 17.81302376, 19.11160043,
       22.02849443, 24.86005763, 24.6577531 , 28.44253746, 17.61

## Đánh giá mô hình linear regression của thư viện

In [55]:
def test(y_pred,dataset_y_test):
    x=y_pred-dataset_y_test
    return np.dot(x.T,x)/len(x)

In [56]:
print(test(y_pred1,dataset_y_test))

33.05700173652929


## Đánh giá mô hình linear regression tự viết

In [57]:
print(test(y_pred2,dataset_y_test))

33.057001736540826
